# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on:
  push:
    branches:
      - main

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the repo
        uses: actions/checkout@v4 # This is a reference to some code to run

      # This step installs the Node version we want
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: npm install

      # Zip the application files
      - name: Zip application
        run: zip -r sandra-acebook.zip .


      #deploy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name sandra-acebook \
          --ignore-hidden-files \
          --s3-location s3://sandra-acebook/sandra-acebook.zip \
          --source .


      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
          --application-name sandra-acebook\
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name sandra-deployment-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket= sandra-acebook,key=sandra-acebook.zip,bundleType=zip \
